"""Chinese display names for supported football clubs."""

import re
import unicodedata


def _normalize(value: str) -> str:
    """Normalize accents, punctuation, and case for provider aliases."""

    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", " ", ascii_value.casefold()).strip()


_RAW_TEAM_NAMES = {
    # Premier League
    "Arsenal": "阿森纳",
    "Aston Villa": "阿斯顿维拉",
    "Bournemouth": "伯恩茅斯",
    "Brentford": "布伦特福德",
    "Brighton": "布莱顿",
    "Brighton and Hove Albion": "布莱顿",
    "Brighton & Hove Albion": "布莱顿",
    "Burnley": "伯恩利",
    "Chelsea": "切尔西",
    "Crystal Palace": "水晶宫",
    "Everton": "埃弗顿",
    "Fulham": "富勒姆",
    "Leeds United": "利兹联",
    "Liverpool": "利物浦",
    "Manchester City": "曼彻斯特城",
    "Manchester United": "曼联",
    "Newcastle United": "纽卡斯尔联",
    "Nottingham Forest": "诺丁汉森林",
    "Sunderland": "桑德兰",
    "Tottenham Hotspur": "托特纳姆热刺",
    "West Ham United": "西汉姆联",
    "Wolverhampton Wanderers": "狼队",
    "Wolverhampton": "狼队",
    "Coventry City": "考文垂",
    "Hull City": "赫尔城",
    "Ipswich Town": "伊普斯维奇",
    # La Liga
    "Alaves": "阿拉维斯",
    "Deportivo Alaves": "阿拉维斯",
    "Athletic Club": "毕尔巴鄂竞技",
    "Athletic Bilbao": "毕尔巴鄂竞技",
    "Atletico Madrid": "马德里竞技",
    "Barcelona": "巴塞罗那",
    "Celta Vigo": "维戈塞尔塔",
    "Elche": "埃尔切",
    "Espanyol": "西班牙人",
    "Getafe": "赫塔费",
    "Girona": "赫罗纳",
    "Las Palmas": "拉斯帕尔马斯",
    "Levante": "莱万特",
    "Mallorca": "马略卡",
    "Malaga": "马拉加",
    "Osasuna": "奥萨苏纳",
    "Rayo Vallecano": "巴列卡诺",
    "Real Betis": "皇家贝蒂斯",
    "Real Madrid": "皇家马德里",
    "Real Oviedo": "皇家奥维耶多",
    "Real Sociedad": "皇家社会",
    "Sevilla": "塞维利亚",
    "Valencia": "瓦伦西亚",
    "Villarreal": "比利亚雷亚尔",
    "Fiorentina": "佛罗伦萨",
    "Ferencvaros": "费伦茨瓦罗斯",
    "Ferencváros": "费伦茨瓦罗斯",
    "Deportivo": "拉科鲁尼亚",
    "Schalke 04": "沙尔克04",
    "FC Cologne": "科隆",
    "Spain": "西班牙",
    "Deportivo La Coruna": "拉科鲁尼亚",
    "Deportivo de A Coruna": "拉科鲁尼亚",
    "Racing de Santander": "桑坦德竞技",
    "Racing Santander": "桑坦德竞技",
    # Chinese Super League
    "Beijing Guoan": "北京国安",
    "Changchun Yatai": "长春亚泰",
    "Chengdu Rongcheng": "成都蓉城",
    "Chongqing Tonglianglong": "重庆铜梁龙",
    "Dalian Yingbo": "大连英博",
    "Henan": "河南队",
    "Henan FC": "河南队",
    "Meizhou Hakka": "梅州客家",
    "Liaoning Tieren": "辽宁铁人",
    "Qingdao Hainiu": "青岛海牛",
    "Qingdao West Coast": "青岛西海岸",
    "Shandong Taishan": "山东泰山",
    "Shanghai Port": "上海海港",
    "Shanghai Shenhua": "上海申花",
    "Shenzhen Peng City": "深圳新鹏城",
    "Tianjin Jinmen Tiger": "天津津门虎",
    "Wuhan Three Towns": "武汉三镇",
    "Yunnan Yukun": "云南玉昆",
    "Zhejiang Professional": "浙江队",
    "Zhejiang FC": "浙江队",
}

TEAM_NAMES_ZH = {_normalize(name): chinese_name for name, chinese_name in _RAW_TEAM_NAMES.items()}

_RAW_PLAYER_NAMES = {
    # Valencia and Real Betis names most likely to appear in the current La Liga view.
    "Hugo Duro": "乌戈·杜罗",
    "Dani Raba": "丹尼·拉巴",
    "Luis Rioja": "路易斯·里奥哈",
    "Javi Guerra": "哈维·格拉",
    "Pepelu": "佩佩卢",
    "André Almeida": "安德烈·阿尔梅达",
    "Andre Almeida": "安德烈·阿尔梅达",
    "Arnaut Danjuma": "阿尔诺·丹朱马",
    "Diego López": "迭戈·洛佩斯",
    "Diego Lopez": "迭戈·洛佩斯",
    "Jesús Vázquez": "赫苏斯·巴斯克斯",
    "Jesus Vazquez": "赫苏斯·巴斯克斯",
    "César Tárrega": "塞萨尔·塔雷加",
    "César Tárrega Requeni": "塞萨尔·塔雷加",
    "Cesar Tarrega": "塞萨尔·塔雷加",
    "Cesar Tarrega Requeni": "塞萨尔·塔雷加",
    "Giorgi Mamardashvili": "乔治·马马尔达什维利",
    "Sergio Canós": "塞尔希奥·卡诺斯",
    "Sergio Canos": "塞尔希奥·卡诺斯",
    "S. Canos": "塞尔希奥·卡诺斯",
    "Aliou Dieng": "阿利乌·迪昂",
    "Jérémy Doku": "杰里米·多库",
    "Abde Ezzalzouli": "阿卜杜·埃扎尔祖利",
    "Giovani Lo Celso": "乔瓦尼·洛塞尔索",
    "G. Lo Celso": "乔瓦尼·洛塞尔索",
    "Marc Bartra": "马克·巴尔特拉",
    "Isco": "伊斯科",
    "Aitor Ruibal": "阿伊托尔·鲁瓦尔",
    "Nabil Fekir": "纳比勒·费基尔",
    "Borja Iglesias": "博尔哈·伊格莱西亚斯",
    "Antony": "安东尼",
    "Vicent Abril": "文森特·阿布里尔",
    "S. Dimitrievski": "迪米特列夫斯基",
    "Cristian Rivero": "克里斯蒂安·里韦罗",
    "Copete": "科佩特",
    "J. Copete": "科佩特",
    "Iker Córdoba": "伊克尔·科尔多瓦",
    "Iker Cordoba": "伊克尔·科尔多瓦",
    "J. de Haas": "德哈斯",
    "J. De Haas": "德哈斯",
    "D. Lopez": "迭戈·洛佩斯",
    "D. Foulquier": "迪米特里·福尔基耶",
    "A. Mari": "阿尔贝托·马里",
    "L. Rioja": "路易斯·里奥哈",
    "M. Diakhaby": "迪亚卡比",
    "Joel Fontanet": "乔尔·丰塔内特",
    "José Gayà": "何塞·加亚",
    "Jose Gaya": "何塞·加亚",
    "Aaron Mayol": "阿隆·马约尔",
    "Marcos Navarro": "马科斯·纳瓦罗",
    "A. Panach": "帕纳奇",
    "Rubo Iranzo": "鲁博·伊兰佐",
    "M. Martinez": "马丁内斯",
    "G. Rodríguez": "吉列尔莫·罗德里格斯",
    "G. Rodriguez": "吉列尔莫·罗德里格斯",
    "R. Sato": "佐藤",
    "F. Ugrinic": "乌格里尼奇",
    "Aimar Blázquez": "艾马尔·布拉斯克斯",
    "Aimar Blazquez": "艾马尔·布拉斯克斯",
    "David Otorbi": "大卫·奥托尔比",
    "U. Sadiq": "萨迪克",
    "Pablo Carmine Maffeo Becerra": "巴勃罗·马费奥",
    "J. Dura": "杜拉",
    "Diego Conde": "迭戈·孔德",
    "D. Conde": "迭戈·孔德",
    "Manu González": "马努·冈萨雷斯",
    "Manu Gonzalez": "马努·冈萨雷斯",
    "Álvaro Valles": "阿尔瓦罗·巴列斯",
    "Alvaro Valles": "阿尔瓦罗·巴列斯",
    "Héctor Bellerín": "贝莱林",
    "Hector Bellerin": "贝莱林",
    "Pablo Busto": "帕布洛·布斯托",
    "C. De Roa": "德罗阿",
    "Junior Firpo": "菲尔波",
    "Fran García": "弗兰·加西亚",
    "Fran Garcia": "弗兰·加西亚",
    "V. Gómez": "戈麦斯",
    "V. Gomez": "戈麦斯",
    "Diego Llorente": "迭戈·略伦特",
    "Natan": "纳坦",
    "Ángel Ortiz": "安赫尔·奥尔蒂斯",
    "Angel Ortiz": "安赫尔·奥尔蒂斯",
    "F. Bernal": "伯纳尔",
    "G. Bouare": "布瓦雷",
    "Ivan Corralejo": "伊万·科拉列霍",
    "N. Deossa": "德奥萨",
    "Álvaro Fidalgo": "阿尔瓦罗·菲达尔戈",
    "Alvaro Fidalgo": "阿尔瓦罗·菲达尔戈",
    "Pablo Fornals": "福纳尔斯",
    "Marc Roca": "马克·罗卡",
    "Pablo García": "巴勃罗·加西亚",
    "Pablo Garcia": "巴勃罗·加西亚",
    "C. Hernández": "埃尔南德斯",
    "C. Hernandez": "埃尔南德斯",
    "Iker Losada": "伊克尔·洛萨达",
    "J. A. Morante": "莫兰特",
    "J. Morante": "莫兰特",
    "A. Ezzalzouli": "阿卜杜·埃扎尔祖利",
    "G. Petit": "佩蒂",
    "A. Ruibal": "阿伊托尔·鲁瓦尔",
    "Rodrigo Riquelme": "罗德里戈·里克尔梅",
    "Cucho Hernández": "库乔·埃尔南德斯",
    "Cucho Hernandez": "库乔·埃尔南德斯",
    "Pablo Fornals": "福纳尔斯",
    "Pablo García": "巴勃罗·加西亚",
    "Iker Losada": "伊克尔·洛萨达",
    # Real Madrid current squad
    "Thibaut Courtois": "蒂博·库尔图瓦",
    "Andriy Lunin": "安德烈·卢宁",
    "Sergio Mestre": "塞尔希奥·梅斯特雷",
    "Antonio Rüdiger": "安东尼奥·吕迪格",
    "Denzel Dumfries": "邓弗里斯",
    "Ferland Mendy": "费兰·门迪",
    "Trent Alexander-Arnold": "特伦特·亚历山大-阿诺德",
    "Éder Militão": "埃德尔·米利唐",
    "Ibrahima Konaté": "伊布拉希马·科纳特",
    "Marc Cucurella": "马克·库库雷利亚",
    "Álvaro Carreras": "阿尔瓦罗·卡雷拉斯",
    "Mario Rivas": "马里奥·里瓦斯",
    "Dean Huijsen": "迪安·赫伊森",
    "Raúl Asencio": "劳尔·阿森西奥",
    "Bernardo Silva": "贝尔纳多·席尔瓦",
    "Federico Valverde": "费德里科·巴尔韦德",
    "Brahim Díaz": "布拉欣·迪亚斯",
    "Aurélien Tchouaméni": "奥雷利安·琼阿梅尼",
    "Eduardo Camavinga": "爱德华多·卡马文加",
    "Jude Bellingham": "裘德·贝林厄姆",
    "Arda Güler": "阿尔达·居勒尔",
    "Thiago Pitarch": "蒂亚戈·皮塔奇",
    "Jorge Cestero": "豪尔赫·塞斯特罗",
    "Alexis Ciria": "亚历克西斯·西里亚",
    "Kylian Mbappé": "基利安·姆巴佩",
    "Vinícius Júnior": "维尼修斯",
    "Rodrygo": "罗德里戈",
    "Endrick": "恩德里克",
    "Carlos Espí": "卡洛斯·埃斯皮",
    "Yan Diomande": "扬·迪奥曼德",
    # Real Sociedad current squad
    "Álex Remiro": "亚历克斯·雷米罗",
    "Unai Marrero": "乌奈·马雷罗",
    "Aitor Fraga": "艾托尔·弗拉加",
    "Igor Zubeldia": "伊戈尔·祖贝尔迪亚",
    "Álvaro Odriozola": "阿尔瓦罗·奥德里奥索拉",
    "Aihen Muñoz": "艾亨·穆尼奥斯",
    "Jon Pacheco": "约恩·帕切科",
    "Jon Aramburu": "约恩·阿兰布鲁",
    "Jon Martín": "约恩·马丁",
    "Iñaki Rupérez": "伊纳基·鲁佩雷斯",
    "Luken Beitia": "卢肯·贝蒂亚",
    "Carlos Soler": "卡洛斯·索莱尔",
    "Yangel Herrera": "扬格尔·埃雷拉",
    "Beñat Turrientes": "贝尼亚特·图连特斯",
    "Luka Sučić": "卢卡·苏契奇",
    "Arsen Zakharyan": "阿尔森·扎哈良",
    "Pablo Marín": "巴勃罗·马林",
    "Alex Lebarbier": "亚历克斯·勒巴比耶",
    "Jon Gorrotxategi": "约恩·戈罗查特吉",
    "Mikel Goti": "米克尔·戈蒂",
    "Ibai Aguirre": "伊拜·阿吉雷",
    "Gonçalo Guedes": "贡萨洛·格德斯",
    "Mikel Oyarzabal": "米克尔·奥亚萨瓦尔",
    "Takefusa Kubo": "久保建英",
    "Sergio Gómez": "塞尔希奥·戈麦斯",
    "Ander Barrenetxea": "安德·巴雷内切亚",
    "Jon Karrikaburu": "约恩·卡里卡布鲁",
    "Orri Óskarsson": "奥里·奥斯卡松",
    "Alex Marchal": "亚历克斯·马尔查尔",
    "Job Ochieng": "乔布·奥琼",
    "Gorka Carrera": "戈尔卡·卡雷拉",
    # Provider initials and academy aliases used in fixture squads
    "T. Courtois": "蒂博·库尔图瓦",
    "J. Navarro Jimenez": "赫苏斯·纳瓦罗·希门尼斯",
    "I. Voloshyn": "伊万·沃洛申",
    "Diego Aguado": "迭戈·阿瓜多",
    "T. Alexander-Arnold": "特伦特·亚历山大-阿诺德",
    "J. Aramburu": "约恩·阿兰布鲁",
    "L. Fati": "法蒂",
    "Jesús Fortea": "赫苏斯·福尔特亚",
    "D. Huijsen": "迪安·赫伊森",
    "David Jiménez": "大卫·希门尼斯",
    "I. Konaté": "伊布拉希马·科纳特",
    "J. Martinez": "哈维·马丁内斯",
    "F. Mendy": "费兰·门迪",
    "M. Serrano": "马科斯·塞拉诺",
    "J. Cestero Sancho": "豪尔赫·塞斯特罗·桑切斯",
    "Manuel Ángel": "曼努埃尔·安赫尔",
    "J. Bellingham": "裘德·贝林厄姆",
    "E. Camavinga": "爱德华多·卡马文加",
    "Y. Diomande": "扬·迪奥曼德",
    "Álvaro Leiva": "阿尔瓦罗·莱瓦",
    "Ávaro Leiva": "阿尔瓦罗·莱瓦",
    "Daniel Yáñez": "丹尼尔·亚涅斯",
    "T. Folgado": "托尼·福尔加多",
    "K. Kita": "凯塔",
    "Javi López": "哈维·洛佩斯",
    "J. Ochieng": "乔布·奥琼",
    "Rupérez": "鲁佩雷斯",
    "Zubeldia": "伊戈尔·祖贝尔迪亚",
    "Lander Astiazarán": "兰德尔·阿斯蒂亚萨兰",
    "Y. Herrera": "扬格尔·埃雷拉",
    "L. Sučić": "卢卡·苏契奇",
    "Dani Díaz": "丹尼·迪亚斯",
    "T. Kubo": "久保建英",
    "O. Óskarsson": "奥里·奥斯卡松",
    "A. Lunin": "安德烈·卢宁",
    "Álvaro Fernández": "阿尔瓦罗·费尔南德斯",
    "D. Dumfries": "邓弗里斯",
    "A. Rüdiger": "安东尼奥·吕迪格",
    "A. Güler": "阿尔达·居勒尔",
    "A. Tchouaméni": "奥雷利安·琼阿梅尼",
    "F. Valverde": "费德里科·巴尔韦德",
    "A. Ciria": "亚历克西斯·西里亚",
    "Odriozola": "阿尔瓦罗·奥德里奥索拉",
    "A. Zakharyan": "阿尔森·扎哈良",
    "Barrenetxea": "安德·巴雷内切亚",
    "Alex Garcia": "亚历克斯·加西亚",
}
PLAYER_NAMES_ZH = {_normalize(name): chinese_name for name, chinese_name in _RAW_PLAYER_NAMES.items()}


def to_chinese_team_name(name: str) -> str:
    """Return a standard Chinese club name or the provider name when unknown."""

    return TEAM_NAMES_ZH.get(_normalize(name), name)


def to_chinese_player_name(name: str) -> str:
    """Return a reviewed Chinese player name or preserve the source name."""

    return PLAYER_NAMES_ZH.get(_normalize(name), name)
